spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/proposta-cartao
    username: root
    password: 4h0U@ioC
    testWhileIdle: true
    validationQuery: SELECT 1

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:18080/auth/realms/proposta/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    naming:
      implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: info,health,prometheus

  metrics:
    tags:
      ambiente: desenvolvimento
      aplicacao: propostas microsservice
      desenvolvedor: bada bhedia


opentracing:
  jaeger:
    enabled: ${JAEGER_ENABLED:true}
    http-sender:
      url: ${JAEGER_ENDPOINT:http://localhost:14268/api/traces}
    probabilistic-sampler:
      sampling-rate: ${JAEGER_SAMPLER:1}
    service-name: ${spring.application.name}

feign:
  client:
    elegibilidade:
      url: ${FEIGN_URL:http://localhost:9999}
    cartoes:
      url: ${FEIGN_URL:http://localhost:8888/api/cartoes}

associar:
  cartao:
    proposta:
      time:
        schedule: "53000"
